### ISSUE TITLE
Create hanging indents for bulleted and numbered lists

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#576] opened 2016-11-30 15:52 UTC
As seen on the following page: https://beta.fec.gov/registration-and-reporting/get-treasurer/

<img width="681" alt="screen shot 2016-11-30 at 10 40 34 am" src="https://cloud.githubusercontent.com/assets/11636908/20758984/8a50f2a4-b6e9-11e6-90b1-11c00edabff1.png">

**Non-hanging indents (incorrect)**
<img width="420" alt="screen shot 2016-11-30 at 10 50 32 am" src="https://cloud.githubusercontent.com/assets/11636908/20759446/f812cea6-b6ea-11e6-9f58-4ff6bbe47d53.png">
[(image citation)](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjmwuCH69DQAhWBKCYKHRsmBtMQjhwIBQ&url=https%3A%2F%2Fwww.floriskleijne.com%2Fblog-entry%2Fwordpress-hanging-indent%2F&bvm=bv.139782543,d.amc&psig=AFQjCNGCu3EG6SldKMl3Nr8nsZLsvD8hlQ&ust=1480607397278143)

**Hanging indents (correct)**
<img width="257" alt="screen shot 2016-11-30 at 10 50 38 am" src="https://cloud.githubusercontent.com/assets/11636908/20759452/fafef86a-b6ea-11e6-89cc-b9ec51f002f1.png">

[(image citation)](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjV99zT6tDQAhUBUiYKHRkWAWoQjhwIBQ&url=https%3A%2F%2Fanswers.themler.com%2Fquestions%2F18609%2Fhanging-indents-on-lists&bvm=bv.139782543,d.amc&psig=AFQjCNGCu3EG6SldKMl3Nr8nsZLsvD8hlQ&ust=1480607397278143)

**Comment by noahmanger** [comment] 2016-12-02 01:52
I just fixed this:
![image](https://cloud.githubusercontent.com/assets/1696495/20820258/bee46d24-b7ee-11e6-8aa8-d9737abdb58a.png)

The reason was that it wasn't an actual `<ul>` list, it was just a series of `<p>` with bullets at the beginning. My guess is it was just a copy and paste thing. 

@emileighoutlaw do you know if we used this technique on other pages? If so, we can just fix it by making them actual lists. No updates to styles required.

**Comment by emileighoutlaw** [comment] 2016-12-02 15:26
I can take a look at the other CMS pages — I just need to make sure they use this bullet style, right?

<img width="925" alt="screen shot 2016-12-02 at 9 25 53 am" src="https://cloud.githubusercontent.com/assets/10552702/20839227/656a8552-b871-11e6-8a53-dc6bf1ec0328.png">

**Comment by noahmanger** [comment] 2016-12-02 17:12
Exactly.

**Comment by emileighoutlaw** [comment] 2016-12-02 17:37
Okay— confirmed and corrected all the bullets in the registration and reporting section and the press section. Should we go back and look at the bullets in the Latest updates feed documents? (Might be a good task for someone on the FEC side?)

**Comment by noahmanger** [comment] 2016-12-02 18:37
Nah. I don't think we need to do that. This seems to be a one-off copy-and-paste mistake. I'm going to close this.

**Closed by noahmanger** 2016-12-02 18:37 UTC
